Review file list sorting fix
vorpal-research/kotoed pull request #102
Opened 2020-10-28 13:48 UTC by h31

2020-10-28 17:52 UTC, gagarski requested changes

2020-11-03 15:28 UTC, h31 commented on kotoed-js/src/main/ts/code/actions.ts
> +                typeOrder.indexOf(a.type) - typeOrder.indexOf(b.type)
Там же два элемента, мапу создавать дольше будет, чем перебрать их

2020-11-06 16:08 UTC, h31 commented on kotoed-js/src/main/ts/code/actions.ts
> +                typeOrder.indexOf(a.type) - typeOrder.indexOf(b.type)
Посмотрел свежим взглядом, вариант с массивом довольно сложно читается. Переделал на мапу из immutable.js.

2020-11-06 16:10 UTC, h31 commented on kotoed-js/src/main/ts/code/actions.ts
> +                    a.type != b.type ? typeSorter(a, b) : naturalSorter(a.name, b.name)
> typeSorter вроде бы даже сейчас возвращает 0 при равенстве

Да. Не очень понял, о чем речь

>  вроде как явное сравнение на равенство приплетать тут не нужно: typeSorter(a, b) || naturalSorter(a.name, b.name).

Согласен, исправил

2020-11-06 17:14 UTC, h31 commented on kotoed-js/src/main/ts/code/actions.ts
> +                typeOrder.indexOf(a.type) - typeOrder.indexOf(b.type)
Я ещё подумывал, чтобы сделать `FileType` enum-ом, но пока не вижу, какие профиты может принести такое решение

2020-11-06 17:26 UTC, gagarski approved these changes

2020-11-06 17:35 UTC, gagarski commented on kotoed-js/src/main/ts/code/actions.ts
> +                typeOrder.indexOf(a.type) - typeOrder.indexOf(b.type)
Профиты, вероятно, в том, что для них есть runtime-операции. Почему везде type union, а не енумы - не помню. Кажется, это было связано с тем, что требовалось вмешательство при сериализации/десериализации данных с сервера (а type union из строк - это просто строка в рантайме), а возможно я не до конца в них разобрался.

2020-11-17 18:09 UTC, merged