New grading system
vorpal-research/kotoed pull request #95
Opened 2020-09-04 14:30 UTC by h31

Часть, отвечающую за формирование отчета (`calcScore`), я особо не трогал, потому что не обговаривались требования к отчету.

2020-09-04 14:32 UTC, h31 commented
![image](https://user-images.githubusercontent.com/3375923/92250752-88927b00-eed4-11ea-8daf-fee27ae12849.png)

2020-09-04 16:28 UTC, gagarski commented
> Часть, отвечающую за формирование отчета (calcScore), я особо не трогал, потому что не обговаривались требования к отчету.

(на всякий случай) Вообще, кажется важным, нужно обговорить требования и сделать, без этого у нас пропасть в грейдинге между котоедом и гуглотаблицами.

2020-09-07 13:55 UTC, ice-phoenix requested changes

2020-09-07 13:55 UTC, ice-phoenix commented on kotoed-server/test/main/kotlin/org/jetbrains/research/kotoed/api/ReportTest.kt
> +    private val reportVerticle = ReportVerticle()
Совсем по нормальному следовало бы использовать механизмы Vert.x для интеграции с тестами, разворачивать вертикаль "по-боевому" и все такое. Но так как тут мы знаем, что вертикаль у нас тупенькая и простенькая, можно и так.

2020-09-07 13:55 UTC, ice-phoenix commented on kotoed-server/test/main/kotlin/org/jetbrains/research/kotoed/api/ReportTest.kt
> +    private val reportVerticle = ReportVerticle()
Ну и в принципе у нас в Котоеде с тестами не очень =)

2020-09-07 13:55 UTC, ice-phoenix commented on kotoed-server/test/main/kotlin/org/jetbrains/research/kotoed/api/ReportTest.kt
> +                "lesson4" to 4, "lesson5" to 3, "lesson6" to 2),
Я бы сравнивал списки так, чтобы результат не зависел от порядка; или у нас гарантируется, что результат возвращается от максимальной оценки до минимальной, а ничьи разбиваются по имени урока?

2020-09-07 13:55 UTC, ice-phoenix commented on kotoed-server/src/main/kotlin/org/jetbrains/research/kotoed/api/ReportVerticle.kt
> +        get() = this.mapNotNull { it.toIntOrNull() }.distinct()
А зачем тут `distinct`?

2020-09-07 13:55 UTC, ice-phoenix commented on kotoed-server/src/main/kotlin/org/jetbrains/research/kotoed/api/ReportVerticle.kt
> +            lessonGrades.sortedByDescending { it.second }.filter { it.second > 0.0 }.take(TAKE_N_HIGHEST_GRADE_LESSONS)
Minor: `filter` тут лучше после `take` с точки зрения избежания лишней работы

2020-09-07 13:55 UTC, ice-phoenix commented on kotoed-server/src/main/kotlin/org/jetbrains/research/kotoed/api/ReportVerticle.kt
> +        return taskGrades.toList().sortedByDescending { it.second }.take(TAKE_N_HIGHEST_GRADE_TASKS)
Alt: вместо `toList()` можно над `entries` дернуть

2020-09-07 13:55 UTC, ice-phoenix commented on kotoed-server/src/main/kotlin/org/jetbrains/research/kotoed/api/ReportVerticle.kt
> +        return totalScore.toDouble() // TODO: Change type to Int everywhere
Вообще, если говорить про общую схему, пользователи могут хотеть и дробные оценки иметь

2020-09-07 13:55 UTC, ice-phoenix commented on kotoed-server/src/main/kotlin/org/jetbrains/research/kotoed/api/ReportVerticle.kt
> +        return totalScore.toDouble() // TODO: Change type to Int everywhere
Так что не понятно, зачем менять все на `Int`

2020-09-07 13:55 UTC, ice-phoenix commented on kotoed-server/src/main/kotlin/org/jetbrains/research/kotoed/api/ReportVerticle.kt
> +        val scores: MutableMap<String, Int> = mutableMapOf()
А может, раз у нас тут появились две связанные по ключу `Map`'ы, сделать датаклассик с оценкой и описанием урока и *одну* `Map`'у над ними?

2020-09-07 13:55 UTC, ice-phoenix commented on kotoed-server/src/main/kotlin/org/jetbrains/research/kotoed/api/ReportVerticle.kt
> +            scoreDescriptions[lesson] = highestGrades.joinToString(separator = " + ") { "${it.second} points for ${it.first}" }
Я бы подумал на тему того, чтобы тут возвращать массив или объект с описаниями уроков и оценок, а делать из него что-то человекочитаемое уже на фронте.

2020-09-10 21:03 UTC, h31 commented on kotoed-server/src/main/kotlin/org/jetbrains/research/kotoed/api/ReportVerticle.kt
> +        get() = this.mapNotNull { it.toIntOrNull() }.distinct()
Потому что в JSON-е с результатами тестирования записи о Tests и RandomTests идут отдельно, и каждая запись включает в себя тег тестового метода. Чуть ниже есть такой код: `flatMap { it.tags }`. Если тег есть и в Tests, и в RandomTests, то мы получим два тега. Если теги одинаковые, то всё нормально (штатная ситуация), и поэтому мы можем склеить их в один тег с помощью `distinct`. Если теги разные, то это говорит о баге в тестах, в таком случае теги не склеиваются, а в методе `grade` будет выброшено исключения.

2020-09-10 21:08 UTC, h31 commented on kotoed-server/test/main/kotlin/org/jetbrains/research/kotoed/api/ReportTest.kt
> +    private val reportVerticle = ReportVerticle()
Была мысль вынести расчеты в отдельный класс. Т.е. расчеты отдельно, Vert.x и БД отдельно. Не знаю, насколько это оправданно, `ReportVerticle` не очень большой.

2020-09-15 13:27 UTC, merged